version: 2

jobs:
  test:
    machine:
      enabled: true
      image: circleci/classic:edge

    steps:
      - checkout

      # we need to use nvm to update node and newest yarn (workspace support)
      - run: ./.circleci/install-yarn.sh
      # needed to download and unpack metamask bundle
      - run: sudo apt-get install -y bsdtar

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      # turns out that it's the same as lerna bootstrap when using workspaces so we dont need to install lerna
      - run: source /opt/circleci/.nvm/nvm.sh && yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: source /opt/circleci/.nvm/nvm.sh && yarn build

      - run: source /opt/circleci/.nvm/nvm.sh && yarn test

workflows:
  version: 2

  mainflow:
    jobs:
      - test
